# train: ../train/images
# val: ../valid/images
# test: ../test/images

# nc: 2
# names: ['0', 'object']

# roboflow:
#   workspace: college-e9cj2
#   project: license-plate-detection-l8xs4
#   version: 1
#   license: CC BY 4.0
#   url: https://universe.roboflow.com/college-e9cj2/license-plate-detection-l8xs4/dataset/1

# Train/val/test sets' image folders
train: ./data/lp/train/images
val: ./data/lp/valid/images  # This dataset uses 'valid'
test: ./data/lp/test/images

# Number of classes
nc: 1

# Class names
names: ['license_plate']